spring.application.name=citas_medicas
#
server.port=9090

#JPA
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

#MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/citas_medicas_db
spring.datasource.username=root
spring.datasource.password=

#JWT
jwt.secret=aEIu9S7cvZUnPJWezau3rKUCxj4BLtpCVzhVSyam93prJOxofs7688P0OD5tmTIsLL6u7G9HpXvT

logging.level.org.hibernate.SQL=DEBUG